"""Auth helpers for API-key, JWT tokens, local users and OAuth providers."""

from __future__ import annotations

from ._crypto import (
    _b64url_decode,
    _b64url_encode,
    _hash_password,
    _hash_token,
    _verify_password,
)
from .constants import (
    ACCESS_TOKEN_TYPE,
    AUTH_OAUTH_PROVIDER_RECORD_TYPE,
    AUTH_OAUTH_STATE_RECORD_TYPE,
    AUTH_POLICY_RECORD_TYPE,
    AUTH_REFRESH_RECORD_TYPE,
    AUTH_USER_RECORD_TYPE,
    DEFAULT_AUTH_SECRET,
    ENV_OAUTH_PROVIDER_MAPPINGS,
    FALSE_ENV_VALUES,
    OAUTH_PROVIDER_PRESETS,
    PRODUCTION_ENVIRONMENTS,
    REFRESH_TOKEN_TYPE,
    TRUE_ENV_VALUES,
)
from .oauth_flow import (
    _fetch_oauth_userinfo,
    _resolve_oauth_user_identity,
    begin_oauth_authorization,
    exchange_oauth_authorization_code,
)
from .oauth_providers import (
    _env_oauth_provider_specs,
    _find_oauth_provider_record,
    _oauth_provider_preset,
    _sanitize_oauth_provider,
    diagnose_oauth_provider,
    list_oauth_providers,
    sync_env_oauth_providers,
    upsert_oauth_provider,
)
from .oauth_states import (
    _backend_public_base_url,
    _find_oauth_state_record,
    _frontend_public_origin,
    _mark_oauth_state_used,
    _persist_oauth_state,
    _pkce_challenge,
)
from .policy import (
    _load_policy,
    get_auth_policy,
    update_auth_policy,
)
from .runtime import (
    auth_status,
    get_current_user_optional,
    oauth2_scheme_optional,
)
from .secrets import (
    _auth_secret,
    _env_auth_required,
    _env_bool_value,
    _env_flag,
    is_auth_secret_production_ready,
    is_production_environment,
)
from .tokens import (
    _default_access_ttl,
    _default_refresh_ttl,
    _find_refresh_session,
    _issue_token_bundle,
    _normalize_scope_items,
    _persist_refresh_session,
    _sanitize_refresh_session,
    create_access_token,
    create_refresh_token,
    list_refresh_sessions,
    refresh_access_token,
    revoke_refresh_session,
    verify_access_token,
)
from .users import (
    _find_linked_oauth_user,
    _find_user_record,
    _sanitize_user,
    _upsert_oauth_user,
    authenticate_local_user,
    list_local_users,
    upsert_local_user,
)

__all__ = [
    "ACCESS_TOKEN_TYPE",
    "AUTH_OAUTH_PROVIDER_RECORD_TYPE",
    "AUTH_OAUTH_STATE_RECORD_TYPE",
    "AUTH_POLICY_RECORD_TYPE",
    "AUTH_REFRESH_RECORD_TYPE",
    "AUTH_USER_RECORD_TYPE",
    "DEFAULT_AUTH_SECRET",
    "ENV_OAUTH_PROVIDER_MAPPINGS",
    "FALSE_ENV_VALUES",
    "OAUTH_PROVIDER_PRESETS",
    "PRODUCTION_ENVIRONMENTS",
    "REFRESH_TOKEN_TYPE",
    "TRUE_ENV_VALUES",
    "_auth_secret",
    "_b64url_decode",
    "_b64url_encode",
    "_backend_public_base_url",
    "_default_access_ttl",
    "_default_refresh_ttl",
    "_env_auth_required",
    "_env_bool_value",
    "_env_flag",
    "_env_oauth_provider_specs",
    "_fetch_oauth_userinfo",
    "_find_linked_oauth_user",
    "_find_oauth_provider_record",
    "_find_oauth_state_record",
    "_find_refresh_session",
    "_find_user_record",
    "_frontend_public_origin",
    "_hash_password",
    "_hash_token",
    "_issue_token_bundle",
    "_load_policy",
    "_mark_oauth_state_used",
    "_normalize_scope_items",
    "_oauth_provider_preset",
    "_persist_oauth_state",
    "_persist_refresh_session",
    "_pkce_challenge",
    "_resolve_oauth_user_identity",
    "_sanitize_oauth_provider",
    "_sanitize_refresh_session",
    "_sanitize_user",
    "_upsert_oauth_user",
    "_verify_password",
    "auth_status",
    "authenticate_local_user",
    "begin_oauth_authorization",
    "create_access_token",
    "create_refresh_token",
    "diagnose_oauth_provider",
    "exchange_oauth_authorization_code",
    "get_auth_policy",
    "get_current_user_optional",
    "is_auth_secret_production_ready",
    "is_production_environment",
    "list_local_users",
    "list_oauth_providers",
    "list_refresh_sessions",
    "oauth2_scheme_optional",
    "refresh_access_token",
    "revoke_refresh_session",
    "sync_env_oauth_providers",
    "update_auth_policy",
    "upsert_local_user",
    "upsert_oauth_provider",
    "verify_access_token",
]
