[pytest]
testpaths = tests
norecursedirs =
    tests/manual
    tests/e2e
    frontend/node_modules
    tests/e2e/node_modules
filterwarnings =
    ignore:y0 and y1 are \(almost\) perfectly colinear.*:statsmodels.tools.sm_exceptions.CollinearityWarning
