#!/usr/bin/env python3
"""Replay ``EtfRotationStrategy`` over a historical window and emit metrics.

Where ``scripts/backtest_etf_rotation.py`` runs the heavier
``PortfolioBacktester`` with execution-engine modelling, this CLI is the
research-mode harness: zero transaction costs, zero slippage, signal
generated by the production strategy and held bar-to-bar. Use it to
answer "does the scoring layer alone have edge over the period?" without
having to triangulate against the live audit log.

Typical use::

    python scripts/backtest_etf_rotation_strategy.py \\
        --prices-csv data/etf_prices.csv \\
        --start-date 2024-06-01 \\
        --end-date 2024-09-01 \\
        --output-md docs/sample_etf_rotation_backtest.md \\
        --output-json output/backtest.json

The ``--enable-policy-signal`` flag toggles ``policy_signal_factor`` for
the run; pair it with two separate runs to A/B the factor over the same
window. The price CSV is the only required input — no live data is
fetched.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections.abc import Sequence
from dataclasses import replace
from pathlib import Path
from typing import Any, Optional

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.daily_etf_signal import (  # noqa: E402
    build_strategy_config,
    load_default_holdings,
    load_policy_industry_signals,
)
from src.backtest.etf_rotation_backtest import (  # noqa: E402
    DEFAULT_INITIAL_CAPITAL,
    DEFAULT_REBALANCE_FREQ_DAYS,
    BacktestReport,
    EtfRotationBacktester,
)
from src.strategy.etf_rotation_config_loader import (  # noqa: E402
    StrategyConfig,
    load_strategy_config,
)

logger = logging.getLogger(__name__)


def load_price_matrix(prices_csv: Path) -> pd.DataFrame:
    """Load a wide CSV (date index, ETF code columns) into a price matrix.

    Same convention as ``scripts/backtest_etf_rotation.py``: dates parsed
    once, the frame is sorted ascending, numeric coerced, ffilled to
    handle staggered listings.
    """

    frame = pd.read_csv(prices_csv, index_col=0)
    frame.index = pd.to_datetime(frame.index)
    return (
        frame.apply(pd.to_numeric, errors="coerce")
        .sort_index()
        .ffill()
        .dropna(how="all")
    )


def run_backtest(
    prices_csv: Path,
    *,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    enable_policy_signal: bool = False,
    rebalance_freq_days: int = DEFAULT_REBALANCE_FREQ_DAYS,
    initial_capital: float = DEFAULT_INITIAL_CAPITAL,
    strategy_config_path: Optional[Path] = None,
    strategy_config_overrides: Optional[dict[str, Any]] = None,
) -> BacktestReport:
    """Top-level orchestration the CLI / API both call into."""

    prices = load_price_matrix(prices_csv)
    strategy_cfg = load_strategy_config(strategy_config_path)

    if strategy_config_overrides:
        strategy_cfg = _apply_strategy_overrides(strategy_cfg, strategy_config_overrides)

    holdings = [h for h in load_default_holdings() if h.code in prices.columns]
    if not holdings:
        # Fall back to using every column in the CSV as the universe — the
        # caller is intentionally probing a custom matrix and shouldn't be
        # tied to the example seed.
        config = build_strategy_config(load_default_holdings(), strategy_cfg)
    else:
        config = build_strategy_config(holdings, strategy_cfg)

    industry_signals: dict[str, dict[str, Any]] = {}
    etf_industry_map: dict[str, str] = dict(strategy_cfg.etf_industry_map)
    if enable_policy_signal:
        loaded, _ = load_policy_industry_signals()
        industry_signals = dict(loaded)

    backtester = EtfRotationBacktester(
        config=config,
        price_history=prices,
        period_start=start_date,
        period_end=end_date,
        policy_signal_factor_enabled=enable_policy_signal,
        industry_signals=industry_signals or None,
        etf_industry_map=etf_industry_map or None,
        rebalance_freq_days=rebalance_freq_days,
        initial_capital=initial_capital,
    )
    return backtester.run()


def _apply_strategy_overrides(
    cfg: StrategyConfig,
    overrides: dict[str, Any],
) -> StrategyConfig:
    """Shallow-merge user overrides into the resolved StrategyConfig.

    Only the top-level ``strategy`` block is supported here — anything
    else stays untouched. Keeps the surface small for v0.1; richer
    overrides land via ``ETF_STRATEGY_CONFIG_PATH``.
    """

    new_strategy = {**cfg.strategy, **overrides}
    return replace(cfg, strategy=new_strategy)


def format_report_markdown(report: BacktestReport) -> str:
    """Render a BacktestReport as a human-readable markdown block."""

    def _pct(value: float) -> str:
        return f"{value:+.2f}%"

    def _opt(value: Optional[float]) -> str:
        return f"{value:.2f}" if value is not None else "n/a"

    lines: list[str] = []
    lines.append("# ETF Rotation Backtest Report")
    lines.append("")
    lines.append(f"- Period: `{report.period_start} → {report.period_end}`")
    lines.append(f"- Bars: {report.n_bars}, Assets: {report.n_assets}")
    lines.append(
        f"- Rebalance cadence: every {report.rebalance_freq_days} bar(s) "
        f"({report.n_rebalances} rebalances)"
    )
    lines.append(
        f"- policy_signal_factor enabled: **{report.policy_signal_factor_enabled}**"
    )
    lines.append("")
    lines.append("## Headline Metrics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Initial capital | ¥{report.initial_capital:,.2f} |")
    lines.append(f"| Final equity | ¥{report.final_equity:,.2f} |")
    lines.append(f"| Total return | {_pct(report.total_return_pct)} |")
    lines.append(f"| Annualized return | {_pct(report.annualized_return_pct)} |")
    lines.append(f"| Sharpe (annualised, daily) | {_opt(report.sharpe_ratio)} |")
    lines.append(f"| Max drawdown | {report.max_drawdown_pct:.2f}% |")
    lines.append(f"| Calmar | {_opt(report.calmar_ratio)} |")
    lines.append(f"| Avg turnover / rebalance | {report.avg_turnover_pct:.2f}% |")
    lines.append(f"| Win rate (rebalance periods) | {report.win_rate * 100:.1f}% |")
    lines.append(
        f"| Comparable equal-weight buy-and-hold | "
        f"{_pct(report.comparable_buy_hold_return_pct)} |"
    )
    lines.append("")
    if report.rebalance_log:
        lines.append("## Rebalances")
        lines.append("")
        lines.append("| Date | Turnover | Period Return | Equity After |")
        lines.append("|---|---|---|---|")
        for row in report.rebalance_log:
            lines.append(
                f"| {row['date']} | {row['turnover'] * 100:.2f}% | "
                f"{row['period_return_pct']:+.2f}% | "
                f"¥{row['equity_after']:,.2f} |"
            )
        lines.append("")
    lines.append("## Caveats")
    lines.append("")
    for caveat in report.caveats:
        lines.append(f"- `{caveat}`")
    lines.append("")
    return "\n".join(lines)


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Replay EtfRotationStrategy on a CSV price matrix.",
    )
    parser.add_argument("--prices-csv", required=True, type=Path)
    parser.add_argument("--start-date", default=None, help="ISO date, inclusive.")
    parser.add_argument("--end-date", default=None, help="ISO date, inclusive.")
    parser.add_argument(
        "--enable-policy-signal",
        action="store_true",
        help="Enable policy_signal_factor for the run (default off).",
    )
    parser.add_argument(
        "--strategy-config",
        type=Path,
        default=None,
        help="Optional path to a strategy.json override file.",
    )
    parser.add_argument(
        "--rebalance-freq-days",
        type=int,
        default=DEFAULT_REBALANCE_FREQ_DAYS,
        help=(
            "Rebalance cadence in business days. Default 5 (~weekly). "
            "Set to 1 for daily, 20 for monthly."
        ),
    )
    parser.add_argument(
        "--initial-capital",
        type=float,
        default=DEFAULT_INITIAL_CAPITAL,
    )
    parser.add_argument("--output-md", type=Path, default=None)
    parser.add_argument("--output-json", type=Path, default=None)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    args = _build_arg_parser().parse_args(argv)

    report = run_backtest(
        args.prices_csv,
        start_date=args.start_date,
        end_date=args.end_date,
        enable_policy_signal=args.enable_policy_signal,
        rebalance_freq_days=args.rebalance_freq_days,
        initial_capital=args.initial_capital,
        strategy_config_path=args.strategy_config,
    )

    payload = report.to_dict()

    if args.output_json is not None:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True),
            encoding="utf-8",
        )

    if args.output_md is not None:
        args.output_md.parent.mkdir(parents=True, exist_ok=True)
        args.output_md.write_text(format_report_markdown(report), encoding="utf-8")

    print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
